apiVersion: v1
kind: ServiceAccount
metadata:
  name: sam-sa
  namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frodo-sa
  namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sauron-sa
  namespace: sauron
---