version: '2'

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - misspell

output:
  formats:
    text: 
      colors: true
    json: {}

run:
  timeout: "5m"
  issues-exit-code: 1
