{{- range $i, $serviceAccount := .Values.serviceAccounts }}
{{ $nameSA := printf "%s-%s" $.Release.Name $serviceAccount | trunc 63 | trimSuffix "-" }}
---
apiVersion: batch/v1
kind: Job
metadata: 
  name: {{ $nameSA }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- toYaml $.Values.labels | nindent 4 }}
spec:
  backoffLimit: {{ $.Values.backoffLimit }}
  template:
    metadata:
      name: {{ $nameSA }}
      namespace: {{ $.Release.Namespace }}
      labels:
      {{- toYaml $.Values.labels | nindent 8 }}
    spec:
      serviceAccount: {{ $serviceAccount }}
      restartPolicy: {{ $.Values.restart.policy }}
      containers:
        - name: {{ $nameSA }}
          image: {{ $.Values.image.name }}:{{ $.Values.image.tag }}
          {{ if gt (len $.Values.image.exec.arguments) 0 -}}
          args: 
          {{- toYaml $.Values.image.exec.arguments | nindent 12 }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: {{ $.Values.resource.limits.memory }}
              cpu: {{ $.Values.resource.limits.cpu }}
{{ end -}}