name: Code Linting

on: 
  push:
    tags:
      - v*
  pull_request:

jobs:
  golintci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.26.4'
      - uses: actions/checkout@v4
      - name: golintci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: -c .golangci.yaml
