name: Security Analysis

on:
  push:
    tags:
      - v*
  pull_request:
    
permissions:
  contents: read
  pull-requests: read

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan . --exclude=readme.md